version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    pre-build:
      commands:
        - echo Nothing to do in the pre_build phase...
    build:
      commands:
        - echo Build started on `date`
        - mvn package
    post_build:
      commands:
        - Build completed on `date`
artifact:
  files:
    - target/codecommit-playground-1.0-SNAPSHOT.jar
