#!/bin/bash


while [ -n "$1" ]; do
    case "$1" in
        -v | --version)
            version="$2"
            if [ -z $version ]; then
                echo "No version argument specified"
                exit
            fi
            shift;;
        *) break
    esac
    shift
done

if [ -n "$version" ]; then
  version="-${version}"
fi
file="codecommit-playground-input${version}.zip"
echo "Creating zip archive $file"

git archive -o "$file" HEAD
